### ISSUE TITLE
center and crop hero image spacing on profile photo

### ISSUE THREAD

**Issue by mikeybkats** [gnoevil/portfolio-301#8]
The current hero image needs centering and cropping.
![image](https://cloud.githubusercontent.com/assets/7930539/20873805/5d2e65f2-ba60-11e6-82c8-8b64543324e3.png)

Proposed solution:
![image](https://cloud.githubusercontent.com/assets/7930539/20874017/bd4a9274-ba62-11e6-9931-c8cea85a34c2.png)

- make a small change to your .profile pic:

```css
.profile-pic {
    height: 150px;
    width: 150px;
    background-image: url(../assets/images/geno-profile-medium.jpg);
    background-size: cover;
}  
```

- try playing around with the height and width as percentages. 
add the property background-position: center
 
``` css
.profile-pic {
    height: 40vh;
    width: 100vw;
    background-image: url(../assets/images/geno-profile-medium.jpg);
    background-size: cover;
    background-position: center;
} 
```

- image could also be higher resolution.
